baseURL = "http://amalara.com/"
languageCode = "en-us"
theme = "menca"
title = "Amalara Game Studio"

#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    identifier = "games"
    name = "Games"
    url = "/games/"
    weight = 3

[params]
  logo = "/images/amalara_logo_v2.svg"
  description = "Amalara Game Studio"

  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "David Garrett"
    author__bio = "Technologist, entrepreneur, part-time game designer."
    author__avatar = "/images/dave.jpg"

  [[params.social]]
    icon = "fa-twitter"
    name = "Twitter"
    link = "https://twitter.com/carpedavid"

  [[params.social]]
    icon = "fa-instagram"
    name = "Instagram"
    link = "https://www.instagram.com/carpedavid/"

  [[params.social]]
    icon = "fa-reddit-alien"
    name = "Reddit"
    link = "https://www.reddit.com/r/amalara/"
  
  [[params.social]]
    icon = "fa-patreon"
    name = "Patreon"
    link = "https://www.patreon.com/amalara"

  [params.hero]
    hero__title = "I'm David Garrett"
    hero__description = "At Amalara Game Studio, I create games that reward creativity, heroism, and teamwork."
    hero__image = "/images/dave_photo.jpg"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false