baseURL = "/"
languageCode = "en-us"
theme = "menca"
title = "Amalara Game Studio"

#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "store"
    name = "Store"
    url = "https://amalara.com"
    weight = 2

[params]
  logo = "images/Logo.svg"
  description = "Amalara Game Studio"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false